---
- name: Install node and npm
  hosts: 159.223.167.141
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new linux user for node app
  hosts: 159.223.167.141
  tasks:
    - name: Create linux user
      user:
        name: nodejs
        comment: Nodejs service account
        group: admin


- name: Deploy nodejs app
  hosts: 159.223.167.141
  become: True
  become_user: nodejs
  tasks:
    - name: Copy nodejs folder to a server
      copy: 
        src: /home/princeton/nodejs-app-main.tar.gz
        dest: /home/nodejs/app-1.0.0.tgz
    - name: Unpack the nodejs tar file
      unarchive: 
        src: /home/princeton/nodejs-app-main.tar.gz
        dest: /home/nodejs
    - name: Install dependencies
      npm:
        path: /home/nodejs/nodejs-app-main/
    - name: Start the application
      command:
        chdir: /home/nodejs/nodejs-app-main/app/
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug:
        msg: "{{app_status.stdout_lines}}"
